name: Auto Commit

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make some changes (example)
        run: echo "// Auto update" >> README.md

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Auto update from GitHub Actions" || echo "No changes"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Marta7799/qimen-backend.git
          git push origin HEAD:main
